server:
  port: 8080
spring:
  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    auth:
      path: /auth/**
      sensitive-headers: Cookie,Set-Cookie
      service-id: auth
    usuario:
      path: /usuario/**
      service-id: usuario

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
