server:
  port: 8080
spring:
  application:
    name: gateway
    config:
      import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: usuario
          uri: lb://usuario
          predicates:
            - Path=/usuario/**
        - id: lancamentos
          uri: lb://lancamentos
          predicates:
            - Path=/lancamentos/**
        - id: email
          uri: lb://email
          predicates:
            - Path=/email/**
