server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlexMotaOliveira/JavAtos/
          search-paths:
            - microservicos/config
          skipSslValidation: true
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
