eureka:
    instance:
        hostname: localhost
        port: 8761
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultzone: http://localhost:8761/eureka

server:
    port: ${PORT:0}
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/javatos?useTimezone=true&serverTimezone=America/Sao_Paulo
        username: root
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        open-in-view: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    main:
        allow-bean-definition-overriding: true
    application:
        name: usuario
