spring:
  mail:
    host: smtp.gmail.com
    password: blxxzpdoeilzigbb
    username: alexmotadev@gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
